# This workflow copies all database pairs defined in copy_pairs.json by calling db-copy.yml for each pair.
name: Multi DB Copy All Pairs

on:
  workflow_dispatch:

jobs:
  discover-pairs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          # Install jq for JSON parsing
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set matrix from copy_pairs.json
        id: set-matrix
        run: |
          # Create a JSON array for matrix.strategy from copy_pairs.json
          PAIRS=$(cat .github/config/copy_pairs.json | jq -c '[.[]]')
          echo "matrix=$PAIRS" >> $GITHUB_OUTPUT

  copy-pairs:
    needs: discover-pairs
    strategy:
      matrix:
        pair: ${{ fromJson(needs.discover-pairs.outputs.matrix) }}
    uses: ./.github/workflows/db-copy.yml
    with:
      source_key: ${{ matrix.pair.source }}
      target_key: ${{ matrix.pair.target }}