name: Multi DB Copy

on:
  workflow_dispatch:
    inputs:
      source_key:
        description: 'Source DB key'
        required: true
      target_key:
        description: 'Target DB key'
        required: true

jobs:
  copy-db:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Delete and Recreate Target DB
        run: |
          RESOURCE_GROUP="your-resource-group"
          SERVER_NAME="your-server-name"
          TARGET_DB="${{ github.event.inputs.target_key }}"
          az postgres flexible-server db delete \
            --resource-group $RESOURCE_GROUP \
            --server-name $SERVER_NAME \
            --database-name $TARGET_DB \
            --yes
          az postgres flexible-server db create \
            --resource-group $RESOURCE_GROUP \
            --server-name $SERVER_NAME \
            --database-name $TARGET_DB

      - name: Dump Source DB
        run: |
          SOURCE_DB="${{ github.event.inputs.source_key }}"
          pg_dump --host=$SOURCE_HOST --username=$SOURCE_USER --dbname=$SOURCE_DB > dump.sql

      - name: Restore Target DB
        run: |
          TARGET_DB="${{ github.event.inputs.target_key }}"
          pg_restore --host=$TARGET_HOST --username=$TARGET_USER --dbname=$TARGET_DB < dump.sql
