name: Start DB Server

on:
  workflow_call:
    inputs:
      azure_resource_group:
        required: true
        type: string
      azure_server_name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  start-db-server:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get current distribution codename
        id: get_dist
        run: echo "AZ_DIST=$(lsb_release -cs)" >> $GITHUB_ENV

      - name: Set Azure CLI version
        run: echo "AZ_VER=2.51.0" >> $GITHUB_ENV

      - name: Install specific version of Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli=${AZ_VER}-1~${AZ_DIST}
          az --version

      - name: Start DB Server
        run: |
          STATE=$(az postgres flexible-server show \
            --resource-group "${{ inputs.azure_resource_group }}" \
            --name "${{ inputs.azure_server_name }}" \
            --query "state" -o tsv)
          if [ "$STATE" == "Ready" ]; then
              echo "${{ inputs.azure_server_name }} is already running"
          else
              az postgres flexible-server start \
                --resource-group "${{ inputs.azure_resource_group }}" \
                --name "${{ inputs.azure_server_name }}"
          fi
