name: Start SNPS Dev (Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'

jobs:
  start-db-server:
    name: Start PostgreSQL Flexible Server
    uses: ./.github/workflows/start-db-server.yml
    with:
      azure_resource_group: SS_RG_SNPS_DEV
      azure_server_name: snpsshift-snps-dev-postgres
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  start-aks-cluster:
    name: Start AKS Cluster
    needs: start-db-server
    uses: ./.github/workflows/start-aks-cluster.yml
    with:
      azure_resource_group: SS_RG_SNPS_DEV
      azure_cluster_name: snpsshift-snps-dev-aks
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
