name: Start Dev

on:
  workflow_dispatch:
  schedule:
    - cron: '55 6 * * *'

env:
  AZURE_RESOURCE_GROUP: Common
  AZURE_SERVER_NAME: rosteringdevsvr14
  AZURE_CLUSTER_NAME: rosteringdevcluster

jobs:
  start-db-server:
    uses: ./.github/workflows/start-db-server.yml
    with:
      azure_resource_group: ${{ inputs.azure_resource_group }}
      azure_server_name: ${{ inputs.azure_server_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  start-aks-cluster:
    needs: start-db-server
    uses: ./.github/workflows/start-aks-cluster.yml
    with:
      azure_resource_group: ${{ inputs.azure_resource_group }}
      azure_cluster_name: ${{ inputs.azure_cluster_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
