name: Stop Dev (Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: '20 7 * * *'

jobs:
  stop-db-server:
    name: Stop PostgreSQL Flexible Server
    uses: ./.github/workflows/stop-db-server.yml
    with:
      azure_resource_group: Common
      azure_server_name: rosteringdevsvr14
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  stop-aks-cluster:
    name: Stop AKS Cluster
    needs: stop-db-server
    uses: ./.github/workflows/stop-aks-cluster.yml
    with:
      azure_resource_group: Common
      azure_cluster_name: rosteringdevcluster
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
